name: Build tools

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Checkout ss-tools
        uses: actions/checkout@v6
        with:
          repository: MakoStar/ss-tools
          path: ss-tools
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ss-tools/target
          key: cargo-cache-${{ hashFiles('ss-tools/Cargo.lock') }}
          restore-keys: cargo-cache-

      - name: Build tools
        run: cargo build -p retrieve-tool -p manifest-tool --release
        working-directory: ss-tools

      - name: Copy tools
        run: |
          mkdir -p tools/RetrieveTool/
          cp ss-tools/target/release/RetrieveTool tools/RetrieveTool/
          
          mkdir -p tools/ManifestTool/
          cp ss-tools/target/release/ManifestTool tools/ManifestTool/

      - name: Auto commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add tools/RetrieveTool/ tools/ManifestTool/
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "update: tools"
            git push
          fi
